# https://github.com/zhs007/tradingcore2
# zerrozhao@gmail.com

FROM debian:buster-slim
WORKDIR /app/tr2
COPY ./dockerhub/trnode2/* /app/tr2/
COPY ./data /app/tr2/data
RUN mkdir output
CMD ["./tc2serv", "./cfg/config.yaml"]