name: Docker gtest

on:
  push:
    branches: [ master, v0.1 ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.gtest --tag tr2tests:$(date +%s)
